In [1]:
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
from dataclasses import dataclass
from datetime import datetime
from math import ceil
import pandas as pd

In [2]:
db = database('trfc.db')

In [3]:
app, rt = fast_app()

In [4]:
data = {
    'min_season': 1921,
    'max_season': 2024,
    'pens_as_draw': 1,
}

venues = ('H', 'A', 'N')

min_games = 10

In [5]:
focus = 'm.manager_name'
focus = 'r.season'
focus = 'r.opposition'

In [ ]:
query = f'''
    SELECT
        {focus},
        COUNT(*) as P,
        COUNT(
            CASE WHEN
                (:pens_as_draw = 0 AND (c.pens_outcome IS NOT NULL AND c.pens_outcome = 'W') OR (c.pens_outcome IS NULL AND r.outcome = 'W'))
            OR 
                (:pens_as_draw = 1 AND r.outcome = 'W')
            THEN 1 END) as W,
        COUNT(
            CASE WHEN
                (:pens_as_draw = 0 AND (c.pens_outcome IS NOT NULL AND c.pens_outcome = 'D') OR (c.pens_outcome IS NULL AND r.outcome = 'D'))
            OR
                (:pens_as_draw = 1 AND r.outcome = 'D')
            THEN 1 END) as D,
        COUNT(
            CASE WHEN 
                (:pens_as_draw = 0 AND (c.pens_outcome IS NOT NULL AND c.pens_outcome = 'L') OR (c.pens_outcome IS NULL AND r.outcome = 'L'))
            OR 
                (:pens_as_draw = 1 AND r.outcome = 'L')
            THEN 1 END) as L,
        SUM(r.goals_for) as GF,
        SUM(r.goals_against) as GA,
        SUM(r.goals_for) - SUM(r.goals_against) as GD,
        ROUND(CAST(COUNT(CASE 
            WHEN (:pens_as_draw = 0 AND (c.pens_outcome IS NOT NULL AND c.pens_outcome = 'W') OR (c.pens_outcome IS NULL AND r.outcome = 'W'))
            OR (:pens_as_draw = 1 AND r.outcome = 'W')
            THEN 1 END) AS FLOAT) / COUNT(*) * 100, 1) as win_pc
    FROM results r
    LEFT JOIN cup_game_details c ON r.game_date = c.game_date
    LEFT JOIN manager_reigns mr ON r.game_date >= mr.mgr_date_from
        AND (r.game_date <= mr.mgr_date_to OR mr.mgr_date_to IS NULL)
    LEFT JOIN managers m ON mr.manager_id = m.manager_id
    LEFT JOIN season_league_tiers slt ON r.season = slt.season AND r.game_type = 'League'
    WHERE CAST(SUBSTRING(r.season, 1, 4) AS INTEGER) >= {data['min_season']} 
        AND CAST(SUBSTRING(r.season, 1, 4) AS INTEGER) <= {data['max_season']}
        AND r.venue IN ('H', 'A', 'N')
    GROUP BY {focus}
    HAVING COUNT(*) >= {min_games}
    ORDER BY P DESC
'''

In [12]:
pens_as_draw = 1

results = db.execute(query, {"pens_as_draw": data['pens_as_draw']})

df = pd.DataFrame(
    results.fetchall(),
    columns=[d[0] for d in results.description]
)

df.query("opposition=='Barnsley'")

   opposition   P   W   D   L  GF  GA  GD  win_pc
29   Barnsley  56  14  18  24  71  87 -16    25.0

In [13]:
pens_as_draw = 0

results = db.execute(query, {"pens_as_draw": pens_as_draw})

df = pd.DataFrame(
    results.fetchall(),
    columns=[d[0] for d in results.description]
)

df.query("opposition=='Barnsley'")

   opposition   P   W   D   L  GF  GA  GD  win_pc
29   Barnsley  56  15  17  24  71  87 -16    26.8